kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-extra-env
data:
  LOGGING_LEVEL_ROOT: INFO
  SERVER_PORT: '8080'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-extra-config
data:
  ENV_VAR1: value1
  application.properties: |
    server.port=8080
    logging.level.root=INFO