kind: Secret
apiVersion: v1
metadata:
  name: secret-extra-env
data:
  ENV_VAR2: dmFsdWUy
  ENV_VAR3: dmFsdWUz
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-extra-config
data:
  ENV_VAR4: dmFsdWU0
  application.secret.properties: c2VydmVyLnBvcnQ9ODA4MApsb2dnaW5nLmxldmVsLnJvb3Q9SU5GTwo=
type: Opaque
